### ISSUE TITLE
Request: Calculator

### ISSUE THREAD

**Issue by chrisalexander** [WebUtils/Platform#1]
From Paul Kinlan: https://twitter.com/Paul_Kinlan/status/496322644070113280

**Comment by mahemoff** [comment]
I could see this evolving into something like Wolfram or Google's widgets, ie a general-purpose "smart command-line" that can answer general-purpose questions (such as unit conversions), but with the added advantage of working purely client-side where it's possible. ie we don't need to be online and make an HTTP connection just to perform basic calculations. It could then appear as a persistent search bar for the launcher, perform auto-completion to quickly locate an app, and also offer to launch external searches.

Don't get me wrong, a simple calculator is fine for v1. Just planting a seed about where it could go.

**Comment by stuartlangridge** [comment]
Simple calculator done at http://stuartlangridge.github.io/webutils-calculator/. How's best to start gathering these things together?

**Comment by chrisalexander** [comment]
This is on the wiki and looks good so closing this request as complete. Thanks for your contribution, @stuartlangridge!

**Comment by stuartlangridge** [comment]
It's not offline, yet. I'd leave this open until it is.

**Comment by chrisalexander** [comment]
I think I will probably open an issue against your repo (perhaps with a PR) once I have put together something of a plan involving offline - this ticks all the boxes for me as they stand at the moment, and I like to celebrate little wins :-) I will however put a comment on the offline ticket about backfilling these previously complete ones when the new requirement does emerge.
