### ISSUE TITLE
Request: currency converter

### ISSUE THREAD

**Issue by stuartlangridge** [WebUtils/Platform#7]
A simple way to say "N USD is how many GBP".

**Comment by mahemoff** [comment]
Google equivalent: https://www.google.com/#q=10+usd+in+gbp

Sources: http://stackoverflow.com/questions/3139879/how-do-i-get-currency-exchange-rates-via-an-api-such-as-google-finance

I tried to make one many years ago and found the sources difficult to come across. Hopefully the above work now.

**Comment by stuartlangridge** [comment]
Simple example done at http://stuartlangridge.github.io/webutils-currencyconverter/ based on the Yahoo Finance API, which is free to access, hooray. Code at https://github.com/stuartlangridge/webutils-currencyconverter.

**Comment by chrisalexander** [comment]
This is on the Wiki and looks awesome, thanks again @stuartlangridge :-)
