### ISSUE TITLE
Request: Stopwatch

### ISSUE THREAD

**Issue by mahemoff** [WebUtils/Platform#9]

**Comment by mahemoff** [comment]
And ideally countdown timer (or link to Google's built-in one http://www.classthink.com/2014/02/23/google-now-built-timer/)

**Comment by PaulKinlan** [comment]
Heh, was just about to write that too.

**Comment by mahemoff** [comment]
Oh! Countdown timer is a good chance to showcase vibration API.

**Comment by chrisalexander** [comment]
http://webutils.github.io/Stopwatch/

Uses the vibration API to notify when a countdown has completed. Design leaves a bit to be desired but I did it pretty quickly - please hit the bug button to report issues!
